# Generated by Django 3.2.1 on 2021-05-10 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210510_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
